---
- name: Setup Vprofile Bastion hosts
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
   - name: Import VPC setup variable
     include_vars: vars/bastion_setup

   - name: Import VPC setup variable
     include_vars: vars/bastion_setup

   - name: Create vprofile ec2 key
     ec2_key:
      name: vprofile-key
      region: "{{region}}"
     register: key_out

   - name: Save private key into file Bastion-key.pem
     copy:
      content: "{{key_out.key.private_key}}"
      dest: "./bastion-key.pem"
      mode: 0600
     when: key_out.changed
   - name: create security group
     ec2_group:
      name: Bastion-host-sg
      description: Security Group for bastion host
      region: "{{region}}"
      vpc_id: "{{vpc-0e97b085f8d962f0f}}"
      rules:
        - porto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{MYIP}}"
      register: BastionSG_out

   - name: Creating Bastion host  
     ec2: 
      key_name: vprofile-key
      region: "{{region}}" 
      instance_type: t2.micro
      image: "{{bastion_ami}}"
      wait: yes
      wait_timeout: 300
      instance_tags:
        Name: "Bastion_host"
        Project: Vprofile
        Owner: Devops Team
      exact_count: 1
      count_tag:
        Name: "Bastion_host"
        Project: Vprofile
        Owner: Devops Team
      group_id: "{{BastionSG_out.group_id}}"
     register: bastionHost_out